# Generated by Django 2.2 on 2020-12-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MiniProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_link', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projectImages')),
                ('is_ml', models.NullBooleanField()),
                ('html', models.FileField(blank=True, null=True, upload_to='projectHTML')),
                ('tools', models.TextField(blank=True, null=True)),
                ('dataset', models.URLField(blank=True, null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Categories')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectType')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
